# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5db778b67b45b01e1e1fe63a038ac866ef79dfefad2f0b8ce1d8eb48001abdb1394863300e0f77a375938df6a47ef5b9444cb0dd0d7c324ee8cb3bb4550beaf4

test:
  secret_key_base: a516f57ffdd12bc512d7e790fbc6654e33d7ef75bae71e6dfbf0f0874cf744782bd6754ee6de56d6c169d3f0502d18741816fc4b13a8ee77a628da1ff5f73f12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
